// <auto-generated />
using System;
using Data.SQL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    [Migration("20231113114033_GenreDataSeed")]
    partial class GenreDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.SQL.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Data.SQL.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Category = "Strategy",
                            Subcategory = "RTS"
                        },
                        new
                        {
                            Id = 8,
                            Category = "RPG",
                            Subcategory = "RPG"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Sports",
                            Subcategory = "Sports"
                        },
                        new
                        {
                            Id = 1,
                            Category = "Races",
                            Subcategory = "Rally"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Action",
                            Subcategory = "TPS"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Adventure",
                            Subcategory = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Puzzle & Skill",
                            Subcategory = "Puzzle & Skill"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Misc.",
                            Subcategory = "Misc."
                        });
                });

            modelBuilder.Entity("Data.SQL.Entities.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });
#pragma warning restore 612, 618
        }
    }
}
